# Generated by Django 5.1.1 on 2024-10-06 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cgpa', '0003_remove_grade_user_semester_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='user',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
